name: Splunk app

on: [push]

jobs:
  appinspect:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Download AppInspect
      run: |
        curl -Ls https://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz -o  splunk-appinspect.tar.gz
    - name: Install AppInspect
      run: |
        python -m pip install --upgrade pip
        pip install splunk-appinspect.tar.gz
    - name: Run AppInspect
      run: |
        cd ${GITHUB_WORKSPACE}
        tar -zcvf SPA.tar.gz appserver bin default static metadata/default.meta README.md
        splunk-appinspect inspect SPA.tar.gz --mode test --max-messages all
        splunk-appinspect inspect SPA.tar.gz --mode test --max-messages all | grep FAILURE > /dev/null && exit 1 || exit 0
    - name: Upload App
      uses: actions/upload-artifact@v1
      with:
        name: SPA.tar.gz
        path: SPA.tar.gz
  server:
    if: success() && github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs: appinspect
    steps:
      - name: Get App
        uses: actions/download-artifact@v1
        with:
          name: SPA.tar.gz
      - name: Unarchive App
        run: |
          mkdir SPA
          tar -xzvf SPA.tar.gz/SPA.tar.gz -C SPA
      - name: Push to server
        uses: trendyminds/github-actions-rsync@master
        with:
          RSYNC_OPTIONS: -avzr --delete
          RSYNC_TARGET: /opt/splunk/etc/apps/
          RSYNC_SOURCE: /SPA
        env:
          SSH_PRIVATE_KEY: ${{ secrets.CI_KEY }}
          SSH_USERNAME: ${{ secrets.CI_USERNAME }}
          SSH_HOSTNAME: ${{ secrets.CI_HOSTNAME }}
