name: Splunk app

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [2.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download AppInspect
      run: |
        curl -Ls https://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz -o  splunk-appinspect.tar.gz
    - name: Install AppInspect
      run: |
        python -m pip install --upgrade pip
        pip install splunk-appinspect.tar.gz
    - name: Run AppInspect
      run: |
        cd ${GITHUB_WORKSPACE}
        git archive HEAD --worktree-attributes --format=tar | gzip > SPA.tar.gz
        splunk-appinspect inspect SPA.tar.gz --mode precert
