name: Splunk app

on: [push]

jobs:
  appinspect:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Download AppInspect
      run: |
        curl -Ls https://download.splunk.com/misc/appinspect/splunk-appinspect-latest.tar.gz -o  splunk-appinspect.tar.gz
    - name: Install AppInspect
      run: |
        python -m pip install --upgrade pip
        pip install splunk-appinspect.tar.gz
    - name: Run AppInspect
      run: |
        cd ${GITHUB_WORKSPACE}
        tar -zcvf SPA.tar.gz appserver bin default static metadata/default.meta README.md
        splunk-appinspect inspect SPA.tar.gz --mode test --max-messages all
        splunk-appinspect inspect SPA.tar.gz --mode test --max-messages all | grep FAILURE > /dev/null && exit 1 || exit 0
    - name: Upload App
      uses: actions/upload-artifact@v1
      with:
        name: SPA.tar.gz
        path: SPA.tar.gz
  server:
    on:
      push:
        branches:
          - master
    runs-on: ubuntu-latest
    needs: appinspect
    steps:
      - name: Get App
        uses: actions/download-artifact@v1
        with:
          name: SPA.tar.gz
      - name: Unarchive App
        run: |
          tar -xzvf SPA.tar.gz
      - name: Push to server
        run: |
          rsync -e "ssh -i <(echo ${{ secrets.CI_KEY }})" -azP SPA ${{ secrets.CI_SERVER }}:/opt/splunk/etc/apps/
          ssh -i <(echo ${{ secrets.CI_KEY }}) ${{ secrets.CI_SERVER }} /opt/splunk/bin/splunk restart
